### ISSUE TITLE
Config uses #define SERIAL

### ISSUE THREAD

**Issue by tolandr** [hjd1964/EncoderBridge#3]
#define SERIAL                     Serial // Serial, specify serial interface for encoder output.                             Option

Should this be?:
#define SERIAL_ONSTEP

**Comment by tolandr** [comment]
I have set this with OnStepX and the Serial Bridge both running on a Teensy 4.1 at 20M UART. No errors using the H39B_B as a closed loop encoder.

// SERIAL PORTS --------------------------------------------------------------------------------------------------------------------
#define SERIAL_ONSTEP             Serial7 // Serial, specify serial interface for encoder output.                             Option
#define SERIAL_BAUD              20000000 // 460800, Or use 460800,230400,115200,etc.                                         Option
#define SERIAL_SWAP                   OFF //    OFF, ON for swapped port or OFF for default port (ESP32/ESP8266 only.)        Infreq


#define BISSC_CLOCK_RATE_KHZ 4000



// ENCODER SUPPORT -----------------------------------------------------------------------------------------------------------------
#define AXIS1_ENCODER         AS37_H39B_B //    OFF, AB, CW_CCW, PULSE_DIR, AS37_H39B_B. RA/Azm Axis (A/MA) & (B/SLO.)        Option
#define AXIS1_ENCODER_REVERSE         OFF //    OFF, ON to reverse the count direction.                                       Option
#define AXIS1_ENCODER_ORIGIN            0 //      0, +/- offset so encoder count is 0 at home (for absolute encoders)         Option

**Comment by hjd1964** [comment]
Change that was never committed, thx.

**Comment by hjd1964** [comment]
And watch that the main branch servo settings changed slightly in my update today.
https://onstep.groups.io/g/main/topic/onstepx_servos/103867497?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,103867497,previd%3D9223372036854775807,nextid%3D1705435822236032812&previd=9223372036854775807&nextid=1705435822236032812
