### ISSUE TITLE
AS37_H39B_B Multi-Turn Counts

### ISSUE THREAD

**Issue by tolandr** [hjd1964/EncoderBridge#5]
From:
src/lib/encoder/bissc/Bissc.h

15  // default to single turn mode
16  #ifndef BISSC_SINGLE
17    #define BISSC_SINGLE_TURN ON
18  #endif

I couldn't find where "BISSC_SINGLE" is ever defined, and the SERVO documentation instructs to define "BISSC_SINGLE_TURN" to ON assuming multi-turn is the default, but it is not:

AS37_H39B_B for Broadcom AS37-H39B BiSS-C absolute encoders.
These encoders use a battery to preserve the multi-turn count, if no battery is used it is best to instruct the driver to ignore the multi-turn part of the count:
#define BISSC_SINGLE_TURN ON

Suggest changing Bissc.h to the following to match the documentation:
15  // default to multi- turn mode
16  #ifndef BISSC_SINGLE_TURN
17    #define BISSC_SINGLE_TURN OFF
18  #endif

**Comment by hjd1964** [comment]
Typo, thanks for the heads up.
